# Generated by Django 4.0.3 on 2022-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_messagefile_tokens_remove_sendmessage_phones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
