# Generated by Django 4.0.3 on 2022-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_remove_sendmessage_user_sendmessage_sended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='notif_history_id',
            field=models.IntegerField(default=0),
        ),
    ]
